b2eb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth.decorators import login_required
admin.autodiscover()
urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', 'systems.views.myclusters_view', name='home'),
                       url(r'^systems/', include('systems.urls')),
                       url(r'^clusters/', include('systems.clusterurls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/',
                           include('accounts.urls',
                                   namespace='accounts')),
                       # url(r'^servertools/', include('servertools.urls',
                       # namespace='servertools')), urls.py missing
                       )
urlpatterns += format_suffix_patterns(urlpatterns)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

systems/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from systems import views
from systems import system_api_views, property_api_views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = patterns('',
                       url(r'^$', views.system_view, name='system_view'),
                       url(r'^api/$', system_api_views.api_root),
                       url(r'^property/api/$', property_api_views.api_root),
                       url(r'^type/(?P<systemType>.*)/$',
                           views.system_view_type, name='system_type'),
                       url(r'^parented/type/(?P<systemType>.*)/$',
                           views.system_view_type_with_parent, name='system_type'),
                       url(r'^detail/(?P<mypk>[0-9]+)/$',
                           views.system_detail, name='system_detail'),
                       url(r'^systemedit/(?P<mypk>-?\d+)/$',
                           views.system_edit, name='system_edit'),
                       url(r'^propertyedit/(?P<mypk>-?\d+)/$',
                           views.property_edit, name='property_edit'),
                       url(r'^propertyadd/(?P<mypk>-?\d+)/(?P<myowner>-?\d+)/$',
                           views.property_edit_link, name='property_add'),
                       url(r'^propertyremove/(?P<mypk>-?\d+)/(?P<myowner>-?\d+)/$',
                           views.property_edit_remove, name='property_remove'),
                       url(r'^systemdelete/(?P<mypk>-?\d+)/$',
                           views.system_delete, name='system_delete'),
                       url(r'^racadm_add/$',
                           views.racadm_system_add,
                           name='system_add'),
                       url(r'^assets.xml$', views.assets_to_xml,
                           name='assets_to_xml'),
                       url(r'^assets.csv$', views.assets_to_csv,
                           name='assets_to_csv'),
                       url(r'^racadm_add_single/$',
                           views.racadm_system_add_single,
                           name='system_add_single'),

                       )


# Login and logout views for the browsable API
urlpatterns += [url(r'^api-auth/$',
                    include('rest_framework.urls',
                            namespace='rest_framework')),
                ]

systems/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.contrib.auth.models import User
from systems.storage import OverwriteStorage
import os
# Create your models here.


def content_filename_name(instance, filename):
    return '/'.join([unicode(instance.key), unicode(instance.value), filename])


class Key(models.Model):
    name = models.CharField(max_length=64, unique=True)
    notes = models.CharField(max_length=512, null=True, blank=True)

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name)

    class Meta:
        ordering = ['name']


class Property(models.Model):
    history = HistoricalRecords()
    key = models.ForeignKey(Key)
    value = models.CharField(max_length=512)
    attachment = models.FileField(
        upload_to=content_filename_name,
        storage=OverwriteStorage(),
        blank=True,
        null=True,
        default=None)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.key.name) + " => " + str(self.value)

    def delete(self):
        try:
            if os.path.isfile(self.attachment.path):
                os.remove(self.attachment.path)
        except:
            print("File detection error occured. Non-existent file.")
        super(Property, self).delete()


class Room(models.Model):
    history = HistoricalRecords()
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(User, null=True, blank=True)
    notes = models.CharField(max_length=512)
    properties = models.ManyToManyField(Property, null=True, blank=True)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " ID =>" + str(self.pk) + \
            ", Name =>" + str(self.name)


class Rack(models.Model):
    history = HistoricalRecords()
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(User, null=True, blank=True)
    room = models.ForeignKey(Room, null=True, blank=True)
    notes = models.CharField(max_length=512)
    properties = models.ManyToManyField(Property, null=True, blank=True)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " ID =>" + str(self.pk) + \
            ", Name =>" + str(self.name)


class HardwareTypes(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=512)

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " " + str(self.description)


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=512)

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " " + str(self.description)


class Disposition(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=512)

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " " + str(self.description)


class Asset(models.Model):  # System/Asset
    history = HistoricalRecords()
    name = models.CharField(max_length=128)
    category = models.ForeignKey(Category, null=True, blank=True)
    owner = models.ForeignKey(User, null=True, blank=True)
    room = models.ForeignKey(Room, null=True, blank=True)
    rack = models.ForeignKey(Rack, null=True, blank=True)
    disposition = models.ForeignKey(Disposition, null=True, blank=True)
    notes = models.CharField(max_length=512, null=True, blank=True)
    properties = models.ManyToManyField(Property, blank=True)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " " + str(self.category) + \
            " ID =>" + str(self.pk)


class System(models.Model):  # System/Asset
    history = HistoricalRecords()
    TYPE_CHOICES = (
        ("server", "Physical Server"),
        ("vm", "Virtual Machine"),
        ("storage", "Permanent Storage Device"),
        ("HDD", "Hard Drives"),
        ("memory", "Memory"),
        ("switch", "Switch"),
        ("router", "Router"),
        ("power_management", "Power Management"),
        ("box", "Box with stuff in it")
    )
    type = models.CharField(max_length=128, choices=TYPE_CHOICES)
    hardware_type = models.ForeignKey(HardwareTypes, null=True, blank=True)
    name = models.CharField(max_length=128)
    servicetag = models.CharField(max_length=64, unique=True)
    dell_id = models.IntegerField(max_length=64, null=True, blank=True)

    SIZE_CHOICES = (
        ("1U", "1U"),
        ("2U", "2U"),
        ("3U", "3U"),
        ("4U", "4U"),
        ("5U", "5U"),
        ("6U", "6U"),
        ("7U", "7U"),
        ("8U", "8U"),
        ("9U", "9U"),
        ("10U", "10U")
    )
    asset_size = models.CharField(
        max_length=64,
        choices=SIZE_CHOICES,
        null=True,
        blank=True)
    owned_ips = models.CharField(max_length=256, null=True, blank=True)
    owned_macs = models.CharField(max_length=256, null=True, blank=True)
    owned_hostnames = models.CharField(max_length=512, null=True, blank=True)

    owner = models.ForeignKey(User, null=True, blank=True)
    room = models.ForeignKey(Room, null=True, blank=True)
    rack = models.ForeignKey(Rack, null=True, blank=True)

    DISPOSITION_CHOICES = (
        (0, 'Out of service, in storage'),
        (5, 'Out of service, newly-received or deployment pending'),
        (6, 'Out of service, in or awaiting repair'),
        (10, 'In service'),
        (80, 'In service, flagged for disposal'),
        (90, 'Out of service, awaiting disposal'),
        (99, 'Out of service, disposed of')
    )
    asset_disposition = models.IntegerField(
        'Disposition', choices=DISPOSITION_CHOICES, default=0)

    notes = models.CharField(max_length=512, null=True, blank=True)
    properties = models.ManyToManyField(Property, null=True, blank=True)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " " + str(self.type) + \
            " Service Tag =>" + str(self.servicetag)


class Cluster(models.Model):
    history = HistoricalRecords()
    name = models.CharField(max_length=128)

    owner = models.ForeignKey(User, null=True, blank=True)
    notes = models.CharField(max_length=512)
    properties = models.ManyToManyField(Property, null=True, blank=True)
    systems = models.ManyToManyField(System, null=True, blank=True)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.name) + " ID =>" + str(self.pk) + \
            ", Name =>" + str(self.name)

systems/templates/systems/clusterdetail.html
{% extends "base_template.html" %}

{% block title %}Cluster {{mySystem.pk}} Details{% endblock %}

{% block styles %}
<style>
iframe.b-iframe {
  height: 40em;
  width: 50em;
  }
</style>
{% endblock %}

{% block headscripts %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/static/js/jquery.bpopup.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
<script src="/static/js/jquery.stickyheader.js"></script>
{% endblock %}


{% block content %}
			<header>
                <td class="property-edit" style="float: right;">{% if request.user.is_superuser %}<a href="" class="minus_button" id="remove_button_cluster" style="float:right;">-</a><a href="" class="edit_button" id="edit_button_cluster" style="float:right; margin-right: .5em;">EDIT</a>{% endif %}</td>
				
                <h1>Cluster <span>{{myCluster.name}} => Detailed properties</span></h1>
                    {% if request.user.is_superuser or request.user == myCluster.owner %}<a href="" class="xfer_button" id="xfer_button_cluster" style="float:right; margin-right: .5em;">Transfer</a>{% endif %}
                <p>Note: {{myCluster.notes}}</p>
			</header>
			
			
						<h2>Systems:</h2>
				<table>
					<thead>
						<tr>
							<th>Name</th>
                            <th>Owner</th>
                            <th>Edit</th>
						</tr>
					</thead>
					<tbody>
{% if myCluster %}
{% for system in myCluster.systems.all %}
<tr><td class="property-name"><a href="/systems/detail/{{system.pk}}/">{{system.name}}</a></td><td class="property-owner">{{system.owner}}</td><td class="property-edit">{% if request.user.is_superuser %}<a href="" class="minus_button" id="remove_button_sys_{{system.pk}}" style="float:right;">-</a>{% endif %}</td></tr>
{% endfor %}
{% endif %}
{% if request.user.is_superuser %}
<tr><td class="property-key"></td><td class="property-value"></td><td class="property-edit"><a href="" class="plus_button" id="plus_system_button" style="float:right;">+</a></td></tr>
{% endif %}						
					</tbody>
				</table>
			
			
			<h2>Properties:</h2>
				<table>
					<thead>
						<tr>
							<th>Key</th>
                            <th>Value</th>
                            <th>File</th>
                            <th>Edit</th>
						</tr>
					</thead>
					<tbody>
{% if myCluster %}
{% for property in myCluster.properties.all %}
<tr><td class="property-key">{{property.key.name}}</td><td class="property-value">{{property.value}}</td><td class="property-file">{% if property.attachment %}<a href="{{ property.attachment.url}}" target = "_empty">{{property.attachment}}</a>{% else %}None{% endif %}</td><td class="property-edit">{% if request.user.is_superuser %}<a href="" class="minus_button" id="remove_button_prop_{{property.pk}}" style="float:right;">-</a><a href="" class="edit_button" id="edit_button_prop_{{property.pk}}" style="float:right; margin-right: .5em;">EDIT</a>{% endif %}</td></tr>
{% endfor %}
{% endif %}
{% if request.user.is_superuser %}
<tr><td class="property-key"></td><td class="property-value"></td><td class="property-edit"><a href="" class="plus_button" id="plus_property_button" style="float:right;">+</a></td></tr>
{% endif %}						
					</tbody>
				</table>
{% endblock %}

{% block footscripts %}
<script>
{% if request.user.is_superuser %}

;(function($) {
    $(function() {
        $('#plus_system_button').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/addsystem/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);

;(function($) {
    $(function() {
        $('#plus_property_button').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/propertyedit/-1/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);
 
{% for property in myCluster.properties.all %}
;(function($) {
    $(function() {
        $('#edit_button_prop_{{property.pk}}').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/propertyedit/{{property.pk}}/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);
 
;(function($) {
    $(function() {
        $('#remove_button_prop_{{property.pk}}').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/removeproperty/{{property.pk}}/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);
{% endfor %}

{% endif %}

{% for system in myCluster.systems.all %}
{% if request.user.is_superuser %}
;(function($) {
    $(function() {
        $('#remove_button_sys_{{system.pk}}').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/removesystem/{{system.pk}}/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery); 
{% endif %}
{% endfor %}


{% if request.user.is_superuser or request.user == myCluster.owner %}
;(function($) {
    $(function() {
        $('#xfer_button_cluster').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/changeowner/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);
{% endif %}

{% if request.user.is_superuser %}
;(function($) {
    $(function() {
        $('#edit_button_cluster').bind('click', function(e) {
            e.preventDefault();
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/edit/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);
 
;(function($) {
    $(function() {
        $('#remove_button_cluster').bind('click', function(e) {
            e.preventDefault();
            
            
            $('#edit_pop_up').bPopup({
        content:'iframe',
        contentContainer:'.content',
        loadUrl: '/clusters/remove/{{mypk}}/' //Uses jQuery.load()
        });
        });
     });
 })(jQuery);
 {% endif %}

</script>
{% endblock %}

systems/templates/systems/clusteredit.html
<html>
<head>
<!-- BEGIN syntax highlighter -->
	<script type="text/javascript" src="/static/js/sh/shCore.js"></script>
	<script type="text/javascript" src="/static/js/sh/shBrushJScript.js"></script>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shCore.css"/>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shThemeDefault.css"/>
    <link href="/static/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">
	<script type="text/javascript">
		SyntaxHighlighter.all();
	</script>
	<!-- END syntax highlighter -->

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.searchabledropdown-1.0.8.min.js"></script>
	<style>
    .required label:after {
    color: #e32;
    content: ' *';
    display:inline;
    }
    .required { font-weight: bold; }
</style>
	
	<script type="text/javascript">
		$(document).ready(function() {
			$("#id_owner").searchable();
		});
	
	
		// demo functions
    $(document).ready(function() {
        $("#id_owner").searchable({
            maxListSize: 500,						// if list size are less than maxListSize, show them all
            maxMultiMatch: 100,						// how many matching entries should be displayed
            exactMatch: false,						// Exact matching on search
            wildcards: true,						// Support for wildcard characters (*, ?)
            ignoreCase: true,						// Ignore case sensitivity
            latency: 200,							// how many millis to wait until starting search
            warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch 
            warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
            zIndex: '1000000'							// zIndex for elements generated by this plugin
        });
    });
	</script>
    
</head>
<body>


{% if form%}
<div style="padding:1em;">
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Save Changes" />
</form>
</div>
{% endif %}




</body>
<footer>
<script src="/static/js/jquery.multi-select.js" type="text/javascript">
</script>

<script type="text/javascript">
$('#id_systems').multiSelect()
</script>

</footer>
</html>

systems/templates/systems/clusters.html
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>B2EB Clusters</title>
		<link rel="stylesheet" type="text/css" href="/static/css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/main.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/component.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/buttons.css" />
		<!--[if IE]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/static/js/jquery.bpopup.min.js"></script>

<style>
iframe.b-iframe {
  height: 40em;
  width: 50em;
  }
</style>

        </head>
    
    
<body>

<!-- Edit mode pop up holder-->

<div style="left: 275.5px; position: absolute; top: 1950px; z-index: 9999; opacity: 1; display: block; height: auto; display:none;" id="edit_pop_up">
        <span class="button b-close"><span>X</span></span>
        <div style="height: auto; width: auto; background-color:white;" class="content"></div>
</div>

    
    
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				<a class="codrops-icon codrops-icon-prev" href="/"><span>STAT - B2EB</span></a>
								<span class="right">{% if request.user.is_authenticated %}
    <span>Welcome, {{ request.user.get_username }}. Thanks for logging in. <a href="/accounts/logout/">Logout</a></span>
{% else %}
    <span><a href="/accounts/login/?next=/clusters/">Please log in.</a></span>
{% endif %}
</span>
			</div>
			<header>
				<h1>Stat B2EB <span>Cluster List</span></h1>	
				<nav class="codrops-demos">
					<!--<a class="current-demo" href="index.html" title="Basic Usage">Basic Usage</a>-->
					<!--<a href="index2.html" title="Biaxial Headers">Biaxial Headers</a>-->
					<!--<a href="index3.html" title="Wide Tables">Wide Tables</a>-->
				</nav>
			</header>
			<!--<div class="component">
				<h2>Basic usage</h2>
				<p>Eating corn</p>-->
				<table>
					<thead>
						<tr>
							<th>Name</th>
							<th>Notes</th>
							<th>Owner</th>
						</tr>
					</thead>
					<tbody>
                    {% if request.user.is_superuser%}
<tr><td class="system-name"></td><td class="system-notes"></td><td class="system-owner"><a href="" id="plus_button" class="plus_button" style="float:right;">+</a></td></tr>               
{% endif %}
                    {% if myClusters %}
{% for cluster in myClusters %}
<tr {%if request.user == cluster.owner %}style = "background-color: #24EC76;border-bottom: 3pt solid #1BD222;border-top: 3pt solid #1BD222;"{% endif %}><td class="system-name"><a href="/clusters/detail/{{cluster.pk}}">{{cluster.name}}</a></td><td class="system-notes">{{cluster.notes}}</td><td class="system-owner">{{cluster.owner}} {% if request.user.is_superuser or request.user == cluster.owner %}<a href="" class="xfer_button" id="xfer_button_{{cluster.pk}}" style="float:right; margin-right: .5em;">Transfer</a>{% endif %}</td></tr>
{% endfor %}
{% endif %}
						
					</tbody>
				</table>
				
		</div><!-- /container -->

		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="/static/js/jquery.stickyheader.js"></script>
	</body>
    <footer>
    <script>
    {% for cluster in myClusters %}
    {% if request.user.is_superuser or request.user == cluster.owner %}
;(function($) {
        $(function() {
            $('#xfer_button_{{cluster.pk}}').bind('click', function(e) {
                e.preventDefault();
                $('#edit_pop_up').bPopup({
            content:'iframe',
            contentContainer:'.content',
            loadUrl: '/clusters/changeowner/{{cluster.pk}}/' //Uses jQuery.load()
            });
            });
         });
     })(jQuery);
     {% endif %}
     {% endfor %}
     
     {% if request.user.is_superuser%}
    ;(function($) {
        $(function() {
            $('#plus_button').bind('click', function(e) {
                e.preventDefault();
                $('#edit_pop_up').bPopup({
            content:'iframe',
            contentContainer:'.content',
            loadUrl: '/clusters/edit/-1/' //Uses jQuery.load()
            });
            });
         });
     })(jQuery);
    {% endif %}
    </script>
    </footer>
</html>

systems/templates/systems/propertyedit.html
<html>
<head>
<!-- BEGIN syntax highlighter -->
	<script type="text/javascript" src="/static/js/sh/shCore.js"></script>
	<script type="text/javascript" src="/static/js/sh/shBrushJScript.js"></script>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shCore.css"/>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shThemeDefault.css"/>
	<script type="text/javascript">
		SyntaxHighlighter.all();
	</script>
	<!-- END syntax highlighter -->

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.searchabledropdown-1.0.8.min.js"></script>
	
	<style>
    .required label:after {
    color: #e32;
    content: ' *';
    display:inline;
    }
    .required { font-weight: bold; }
</style>
    
	<script type="text/javascript">
		$(document).ready(function() {
			$("#id_owner").searchable();
		});
	
	
		// demo functions
    $(document).ready(function() {
        $("#id_owner").searchable({
            maxListSize: 500,						// if list size are less than maxListSize, show them all
            maxMultiMatch: 100,						// how many matching entries should be displayed
            exactMatch: false,						// Exact matching on search
            wildcards: true,						// Support for wildcard characters (*, ?)
            ignoreCase: true,						// Ignore case sensitivity
            latency: 200,							// how many millis to wait until starting search
            warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch 
            warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
            zIndex: '1000000'							// zIndex for elements generated by this plugin
        });
    });
	</script>
    
</head>
<body>


{% if form%}
<div style="padding:1em;">
<form enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Save Changes" />
</form>
</div>
{% endif %}




</body>
<footer>

</footer>
</html>

systems/templates/systems/racadm_add.html
<style>
    .required label:after {
    color: #e32;
    content: ' *';
    display:inline;
    }
    .required { font-weight: bold; }
</style>
<form action="" method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>

systems/templates/systems/redirect_template.html
<html>
    <head>
    
    <style>
    .required label:after {
    color: #e32;
    content: ' *';
    display:inline;
    }
    .required { font-weight: bold; }
</style>
    
        <script>
            window.top.location.href = '{{ redirect_url }}';
        </script>
    </head>
    <body>Redirecting to <a href="{{redirect_url}}" target="_TOP">{{ redirect_url }}</a></body>
</html>

systems/templates/systems/systemedit.html
<html>
<head>
<!-- BEGIN syntax highlighter -->
	<script type="text/javascript" src="/static/js/sh/shCore.js"></script>
	<script type="text/javascript" src="/static/js/sh/shBrushJScript.js"></script>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shCore.css"/>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shThemeDefault.css"/>
	<script type="text/javascript">
		SyntaxHighlighter.all();
	</script>
	<!-- END syntax highlighter -->

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.searchabledropdown-1.0.8.min.js"></script>
	
	
	<script type="text/javascript">
		$(document).ready(function() {
			$("#id_owner").searchable();
		});
	
	
		// demo functions
    $(document).ready(function() {
        $("#id_owner").searchable({
            maxListSize: 500,						// if list size are less than maxListSize, show them all
            maxMultiMatch: 100,						// how many matching entries should be displayed
            exactMatch: false,						// Exact matching on search
            wildcards: true,						// Support for wildcard characters (*, ?)
            ignoreCase: true,						// Ignore case sensitivity
            latency: 200,							// how many millis to wait until starting search
            warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch 
            warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
            zIndex: '1000000'							// zIndex for elements generated by this plugin
        });
    });
	</script>
    
    <style>
    .required label:after {
    color: #e32;
    content: ' *';
    display:inline;
    }
    .required { font-weight: bold; }
</style>
    
</head>
<body>


{% if form%}
<div style="padding:1em;">
<form action="/systems/systemedit/{{mypk}}/" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Save Changes" />
</form>
</div>
{% endif %}




</body>
<footer>

</footer>
</html>